# Generated by Django 4.2.29 on 2026-03-11 04:57

import apps.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True, verbose_name='Slug')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('resumo', models.TextField(max_length=500, verbose_name='Resumo')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de publicação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='posts/', validators=[apps.core.models.validar_imagem], verbose_name='Imagem de capa')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
