# Generated by Django 4.2.29 on 2026-03-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ex: https://www.youtube.com/watch?v=...', verbose_name='URL do vídeo (opcional)'),
        ),
    ]
