# Generated by Django 5.2.12 on 2026-03-11 12:42

import apps.posts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='posts/midias/', validators=[apps.posts.models.validar_midia], verbose_name='Arquivo')),
                ('video_url', models.URLField(blank=True, default='', help_text='Link de vídeo externo (YouTube, Vimeo, etc.)', verbose_name='URL do vídeo externo')),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], default='imagem', max_length=10, verbose_name='Tipo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='posts.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Mídia do Post',
                'verbose_name_plural': 'Mídias do Post',
                'ordering': ['ordem'],
            },
        ),
    ]
