# Generated by Django 5.2.12 on 2026-03-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_mediapost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('geral', 'Geral'), ('destaque', 'Destaque'), ('reuniao', 'Reunião'), ('encontro', 'Encontro'), ('informativo', 'Informativo'), ('cultural', 'Cultural'), ('ambiental', 'Ambiental')], default='geral', help_text='Categoria visual do post.', max_length=20, verbose_name='Categoria'),
        ),
    ]
