# Generated by Django 5.2.12 on 2026-03-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/hora de término'),
        ),
        migrations.AddField(
            model_name='evento',
            name='google_event_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identificador único do evento no Google Calendar (preenchido automaticamente na sincronização).', max_length=512, unique=True, verbose_name='ID do Google Calendar'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Local'),
        ),
    ]
