# Generated by Django 5.2.12 on 2026-03-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_data_fim_evento_google_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='google_event_id',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador único do evento no Google Calendar (preenchido automaticamente na sincronização).', max_length=512, null=True, unique=True, verbose_name='ID do Google Calendar'),
        ),
    ]
