# Generated by Django 5.2.12 on 2026-03-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_evento_google_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='link_opcional',
            field=models.URLField(blank=True, default='', verbose_name='Link opcional'),
        ),
    ]
