# Generated by Django 5.2.12 on 2026-03-11 07:04

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracaosite'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='animacao_folhas_ativa',
            field=models.BooleanField(default=True, help_text='Ativa ou desativa a animação de folhas caindo no site.', verbose_name='Animação de folhas ativa'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='cor_fundo',
            field=models.CharField(blank=True, default='#f5f1eb', help_text='Cor de fundo do site (hex). Usada se não houver imagem de fundo.', max_length=25, verbose_name='Cor de fundo'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='google_calendar_link',
            field=models.URLField(blank=True, default='', help_text='URL pública do Google Calendar para sincronização de eventos.', verbose_name='Link do Google Calendar'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='imagem_fundo',
            field=models.ImageField(blank=True, help_text='Imagem de fundo do site. Exibida com overlay semi-transparente.', null=True, upload_to='site/', validators=[apps.core.models.validar_imagem], verbose_name='Imagem de fundo'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='link_instagram',
            field=models.URLField(blank=True, default='', help_text='URL completa do perfil no Instagram.', verbose_name='Link do Instagram'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='link_telegram',
            field=models.URLField(blank=True, default='', help_text='URL do grupo ou canal no Telegram.', verbose_name='Link do Telegram'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='link_youtube',
            field=models.URLField(blank=True, default='', help_text='URL do canal no YouTube.', verbose_name='Link do YouTube'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='tamanho_logo',
            field=models.PositiveIntegerField(default=120, help_text='Tamanho em pixels do logo no hero. Padrão: 120.', verbose_name='Tamanho do logo (px)'),
        ),
    ]
