# Generated by Django 5.2.12 on 2026-03-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configuracaosite_email_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='menu_posicao',
            field=models.CharField(choices=[('topo', 'Horizontal (topo)'), ('lateral', 'Vertical (lateral direita)')], default='topo', help_text='Define se o menu é exibido no topo (horizontal) ou na lateral direita (vertical).', max_length=10, verbose_name='Posição do menu'),
        ),
    ]
