# Generated by Django 5.2.12 on 2026-03-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_configuracaosite_menu_posicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosite',
            name='menu_posicao',
            field=models.CharField(choices=[('topo', 'Horizontal (topo)'), ('lateral', 'Vertical (lateral esquerda)')], default='lateral', help_text='Define se o menu é exibido no topo (horizontal) ou na lateral esquerda (vertical).', max_length=10, verbose_name='Posição do menu'),
        ),
    ]
