# Generated by Django 5.2.12 on 2026-03-11 19:09

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_configuracaosite_menu_posicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='galeria/', validators=[apps.core.models.validar_imagem], verbose_name='Imagem')),
                ('titulo', models.CharField(blank=True, default='', max_length=200, verbose_name='Título')),
                ('descricao', models.CharField(blank=True, default='', max_length=500, verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Adicionada em')),
            ],
            options={
                'verbose_name': 'Foto da Galeria',
                'verbose_name_plural': 'Fotos da Galeria',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
    ]
